### ISSUE TITLE
Adding Logo

### ISSUE THREAD

**Issue by the-amazing-atharva** [Vincenius/sponsor-ninja#1]
Hey!
I am a beginner here and would like to contribute to this project

I suggest adding the logo to heading and center it along with the title and overall making the README more appealing

If you liked the suggestion do assign me this issue!

Regards

**Comment by Vincenius** [comment]
Hey there :)

Thanks for offering your help! It would be a great help if you'd get the project running locally and could write down the steps in the README for others to follow.

Then you could of course also do some visual improvements, even though I'm not completely sure where you want to add the Logo. Feel free to create a PR and I will check it :)

Cheers,
Vincent

**Comment by the-amazing-atharva** [comment]
Thanks for the reply!

Working on it

**Comment by the-amazing-atharva** [comment]
I am new to running projects locally but I did some research to find the steps.
Could you cross-check it ?

```
# Steps to Get the Project Running Locally
1. Clone the repository to your local machine
   git clone https://github.com/user/repo.git
2. Navigate to the project directory
   cd repo
3. Install the necessary dependencies
   npm install
4. Start the local development server
   npm start
5. Open your browser to http://localhost:3000
```


**OR**

```
# Steps to Get the Project Running Locally
1. Clone the repository to your local machine
   git clone https://github.com/user/repo.git
2. Navigate to the project directory
   cd repo
3. Checkout to the appropriate branch if necessary
   git checkout develop
4. Install the necessary dependencies
   npm install
5. Create a .env file and set environment variables if needed
6. Run database migrations if necessary
   npm run migrate
7. Start the local development server
   npm start
8. Open your browser to http://localhost:3000
```

**Comment by Vincenius** [comment]
Almost - it's more like the second version. Feel free to create a PR with this one and I will do some fine-tuning on it :)

**Comment by the-amazing-atharva** [comment]
Sure !

**Comment by Vincenius** [comment]
Steps are added now. Thanks for your help!
